# ---- Stage 1: Build ----
FROM node:20-alpine AS builder

# Add C libraries required by Tailwind Oxide and Next.js SWC
RUN apk add --no-cache libc6-compat

WORKDIR /app

# Copy package.json and lock file
COPY package*.json ./

# Use standard install so npm fetches the correct Linux optional dependencies
RUN npm install --no-audit --no-fund --loglevel=error

# Copy the rest of the application source code
COPY . .

# Disable telemetry during build
ENV NEXT_TELEMETRY_DISABLED 1

# Build the Next.js application
RUN npm run build


# ---- Stage 2: Production Runner ----
FROM node:20-alpine AS runner

# Add C libraries to the runner
RUN apk add --no-cache libc6-compat

WORKDIR /app

# Set environment variables for production
ENV NEXT_TELEMETRY_DISABLED 1
ENV NODE_ENV production

# Copy the standalone folder from the build stage
COPY --from=builder /app/.next/standalone ./

# Copy the public folder and static assets generated by the build
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/static ./.next/static

# Expose the port the Next.js server listens on
EXPOSE 3000

# Start the Node.js server in standalone mode
CMD ["node", "server.js"]